chore: master브랜치 가드
Signed-off-by: daeyeon ko <rowan@megazone.com>

diff --git a/.github/workflows/dispatch_release_V3.yaml b/.github/workflows/dispatch_release_V3.yaml
--- a/.github/workflows/dispatch_release_V3.yaml
+++ b/.github/workflows/dispatch_release_V3.yaml
@@ -23,6 +23,15 @@ env:
   REF_BRANCH: "master"
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch with regex
+        run: |
+          if [[ ! "${{ github.ref }}" =~ ^refs/heads/(master.*|.*master)$ ]]; then
+            echo "::error::Invalid branch pattern!"
+            exit 1
+          fi
   #  mirinae:
   #    runs-on: ubuntu-latest
   #    steps:
