test (#10)
* feat: 주석, 한글제거

Signed-off-by: daeyeon ko <rowan@megazone.com>

* feat(backend-test): test

Signed-off-by: daeyeon ko <rowan@megazone.com>

* test: test

Signed-off-by: daeyeon ko <rowan@megazone.com>

* chore: workflow_dispatch 테스트

Signed-off-by: daeyeon ko <rowan@megazone.com>

* chore: master브랜치 가드

Signed-off-by: daeyeon ko <rowan@megazone.com>

* test: 불필요한 step제거

Signed-off-by: daeyeon ko <rowan@megazone.com>

* test: 의존성 추가

Signed-off-by: daeyeon ko <rowan@megazone.com>

---------

Signed-off-by: daeyeon ko <rowan@megazone.com>

diff --git a/.github/workflows/dispatch_release.yaml b/.github/workflows/dispatch_release.yaml
--- a/.github/workflows/dispatch_release.yaml
+++ b/.github/workflows/dispatch_release.yaml
@@ -23,6 +23,15 @@ env:
   REF_BRANCH: "master"
 
 jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch with regex
+        run: |
+          if [[ ! "${{ github.ref }}" =~ ^refs/heads/(master.*|.*master)$ ]]; then
+            echo "::error::Invalid branch pattern!"
+            exit 1
+          fi
   #  mirinae:
   #    runs-on: ubuntu-latest
   #    steps:
@@ -56,7 +65,8 @@ jobs:
 
   versioning_and_docker:
     runs-on: ubuntu-latest
-    #    needs: mirinae
+    needs: [check-branch]
+#    needs: [check-branch, mirinae]
     outputs:
       new_commit_sha: ${{ steps.get_sha.outputs.NEW_COMMIT_SHA }}
     steps:
